server: 
  port: 8081
  servlet: 
    context-path: /sso-resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/4865ff4e-a84e-49ca-a5a6-3bc9e823eb87/v2.0
#          issuer-uri: https://sts.windows.net/4865ff4e-a84e-49ca-a5a6-3bc9e823eb87/
          jwk-set-uri: https://login.microsoftonline.com/4865ff4e-a84e-49ca-a5a6-3bc9e823eb87/discovery/v2.0/keys