spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: d2bf0f85-c50e-4498-86d4-1d59fde2f00d
            client-secret: WW6-11Xi-U.-75ZP~I~WXR2djAN5xe~Y8K
            scope: openid,profile,User.Read,email
#            scope: https://graph.microsoft.com/.default
#            scope: d2bf0f85-c50e-4498-86d4-1d59fde2f00d/.default
#            scope: d2bf0f85-c50e-4498-86d4-1d59fde2f00d/.default,openid,profile,User.Read,email
#            scope: https://graph.microsoft.com/.default,openid,profile,User.Read,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: https://login.microsoftonline.com/4865ff4e-a84e-49ca-a5a6-3bc9e823eb87/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/4865ff4e-a84e-49ca-a5a6-3bc9e823eb87/oauth2/v2.0/token
#            user-info-uri: file:///Users/robd/dev/osdev/git/spring-security-oauth/oauth-sso/userinfo.txt
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-info-uri: https://login.microsoftonline.com/4865ff4e-a84e-49ca-a5a6-3bc9e823eb87/openid/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: https://login.microsoftonline.com/4865ff4e-a84e-49ca-a5a6-3bc9e823eb87/discovery/v2.0/keys
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8082
  servlet: 
    context-path: /ui-one
    
logging: 
  level: 
    org.springframework: INFO

resourceserver:
  api:
    url: http://localhost:8081/sso-resource-server/api/foos/
              
